### PR TITLE
Expand arrow mecs, additional minor fixes

### LINKED ISSUE #1920: Arrow pickup tag/mec
Relevant methods:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Arrow.html#getPickupStatus--
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Arrow.html#setPickupStatus-org.bukkit.entity.Arrow.PickupStatus-

Arrow pickup status enums:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Arrow.PickupStatus.html

### PR DESCRIPTION
**Pull request by MusicScore**
Fixes #1920

### CODE REVIEW

File: plugin/src/main/java/net/aufdemrand/denizen/objects/dMaterial.java [hunk 1]
```diff
@@ -469,7 +469,7 @@ public String run(Attribute attribute, dObject object) {
         registerTag("is_plant", new TagRunnable() {
```
Comment (mcmonkey4eva) [inline plugin/src/main/java/net/aufdemrand/denizen/objects/dMaterial.java:477]: This tag is now wrong from the rename

File: plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityArrowDamage.java [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+    public void adjust(Mechanism mechanism) {
+
+        // <--[mechanism]
+        // @object dEntity
+        // @name damage
+        // @input Element
+        // @description
+        // Changes how much damage an arrow/trident will inflict.
+        // @tags
+        // <e@entity.pickup_status>
```
Comment (mcmonkey4eva) [inline plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityArrowDamage.java]: ^ bad copypasta

File: plugin/src/main/java/net/aufdemrand/denizen/objects/properties/item/ItemPotion.java [hunk 3]
```diff
@@ -311,7 +311,7 @@ public void adjust(Mechanism mechanism) {
         // @input dList
         // @description
         // Sets the potion's potion effect(s).
-        // Input is a formed like: Effect,Upgraded,Extended(,Color)|Type,Amplifier,Duration,Ambient,Particles(,Icon)|...
+        // Input is a formed like: Type,Upgraded,Extended(,Color)|Effect,Amplifier,Duration,Ambient,Particles(,Icon)|...
```
Comment (mcmonkey4eva) [inline plugin/src/main/java/net/aufdemrand/denizen/objects/properties/item/ItemPotion.java]: Why was this change made?

Comment (ghost) [reply plugin/src/main/java/net/aufdemrand/denizen/objects/properties/item/ItemPotion.java]: I felt like it better emphasized the difference between potion *types* (base potion) and potion *effects* (has been historically synonymous with status effects). Plus, it better fits with the two server list tags that make that distinction clear (`<server.list_potion_types>` returns a list of potion types, and `<server.list_potion_effects>` returns a list of potion effects).

Comment (mcmonkey4eva) [reply plugin/src/main/java/net/aufdemrand/denizen/objects/properties/item/ItemPotion.java]: You would have to make significant changes to the rest of the `ItemPotion` file to try to make an idea like that work. Throughout the file, `type` and `effect` are used to mean the same concept, and `Effect` is used at various points for the base, and `Type` used for the list of effects. See for ref `
                // @attribute <i@item.potion_effect[<#>].type>`
And as well
```
        // @attribute <i@item.potion_base>
        // Returns the potion effect on this item.
        // In the format Effect,Level,Extended,Splash,Color
```

Comment (ghost) [reply plugin/src/main/java/net/aufdemrand/denizen/objects/properties/item/ItemPotion.java]: Oh, I didn't see that. Can probably open a separate PR for that when I finish up the rest of my potion changes (ItemPotion and EntityPotion), since I believe I fixed that as part of that set of changes.

File: plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityArrowDamage.java [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+    @Override
+    public String getAttribute(Attribute attribute) {
+
+        if (attribute == null) {
+            return "null";
+        }
+
+        // <--[tag]
+        // @attribute <e@entity.damage>
+        // @returns Element
```
Comment (mergu) [inline plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityArrowDamage.java]: Tag should reflect whether it returns a numeric/decimal value

File: plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityArrowDamage.java [hunk 5]
```diff
@@ -0,0 +1,120 @@
...
+        return null;
+    }
+
+    @Override
+    public void adjust(Mechanism mechanism) {
+
+        // <--[mechanism]
+        // @object dEntity
+        // @name damage
+        // @input Element
```
Comment (mergu) [inline plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityArrowDamage.java]: Same as above

**Review by mergu — DISMISSED** [review]

**Comment by MusicScore** [comment]
Reverted the potion meta fix because that really shouldn't be in this PR if I intend for another PR to have that fix.

Otherwise, the rest should stand on its own quite nicely.

**Comment by mcmonkey4eva** [comment]
Yay new things! Thanks!
